#!/usr/bin/php
<?php
 if ($argc == 1 || $argc > 3 || in_array($argv[1], array('--help', '-help', '-h', '-?'))) {
?>

wordmove-database V 1.0
With this script is possible auto insert the remote database data in the Movefile
Made by Mte90 - http://www.mte90.net

  Usage:
  <?php echo $argv[0]; ?> [staging|production|etc]
  
  The first parameter it's needed for get the database data of the host and insert in the Movefile.
  With the --help, -help, -h, or -? options, you can get this help.

<?php
} else {
    if(file_exists('Movefile')) {
        //Read the movefile
        $movefile = yaml_parse(file_get_contents('Movefile'));
        if ($argv[1] != 'local') {
            echo 'Logging on the server...'."\n";
            
            if($movefile[$argv[1]]['ftp']['host'] !== 'host') {
                $connection = ftp_connect($movefile[$argv[1]]['ftp']['host'], 21) 
                or die ('It\'s not possible connect to the server'."\n");
                
                ftp_login($connection, $movefile[$argv[1]]['ftp']['user'], $movefile[$argv[1]]['ftp']['password']) 
                or die('Username or password wrong.'."\n");
                                
                //Move to the folder
                if($movefile[$argv[1]]['wordpress_path'] !== '/var/www/your_site') {
                    ftp_chdir($connection, $movefile[$argv[1]]['wordpress_path']) or die('The path of Wordpress installation is wrong'."\n");
                } else {
                    die ('You don\'t have insert a valid path of Wordpress!'."\n");
                }
                
                //Download the file
                $get = ftp_get($connection, 'wp-config-'.$argv[1].'.php', 'wp-config.php', FTP_ASCII) or die('wp-config.php not founded!'."\n");
                
                //Remove reference to file wp-settings.php
                $config = file_get_contents('wp-config-'.$argv[1].'.php');
                $config = str_replace("require_once(ABSPATH . 'wp-settings.php');", '', $config);
                file_put_contents('wp-config-'.$argv[1].'.php', $config);
                //Include the file cleaned
                include('wp-config-'.$argv[1].'.php');
                
                //Insert value
                $movefile[$argv[1]]['database']['name'] = DB_NAME;
                $movefile[$argv[1]]['database']['user'] = DB_USER;
                $movefile[$argv[1]]['database']['password'] = DB_PASSWORD;
                $movefile[$argv[1]]['database']['host'] = DB_HOST;
                
                //Remove the file downloaded
                unlink('wp-config-'.$argv[1].'.php');
                
                $yaml = yaml_emit($movefile);
                
                file_put_contents('Movefile',$yaml);
                
                echo (!$get) ? 'Download Error!'."\n" : 'Movefile updated!'."\n".'Good job by Mte90!'."\n";
            } else {
                die ('You don\'t have insert a valid FTP host!'."\n");
            }
            
        } else {
            echo 'What are you doing? We are in local, I can not check anything!'."\n";
        }
    } else {
        echo 'ERROR: Missing Movefile!'."\n".'Generate it with `wordmove init`'."\n";
    }
}
?>